PAX_01

[0] {
    0   PAX_CONGRESS_THEATRE_BK    0,0  NONESSSSS
    1   PAX_CONGRESS_CURTAIN       0,0  NONESSSSS
    2   PAX_CONGRESS_FLOOR         0,0  NONESSSSS
};
[2] {
    0   PAX_CONGRESS_DOOR   0,0     NONESSSSS
    1   PAX_CONGRESS_RAIL_C 0,0     NONESSSSS
};
[3] {
    0   PAX_CONGRESS_RAIL_B 0,0     NONESSSSS
};
[4] {
    0   PAX_CONGRESS_RAIL_A 0,0     NONESSSSS
};
[5] {
    0   PAX_CONGRESS_STAND    0,0   NONESSSSS
    1   THEATRE_CHAIRS        0,0   NONESSSSS
};